-- phpMyAdmin SQL Dump
-- version 4.8.0
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Jul 06, 2018 at 08:42 AM
-- Server version: 10.1.31-MariaDB
-- PHP Version: 7.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

CREATE DATABASE hnmdb;
USE hnmdb;
--

-- --------------------------------------------------------

--
-- Table structure for table `account`
--

CREATE TABLE `account` (
  `firstname` varchar(20) NOT NULL,
  `lastname` varchar(20) NOT NULL,
  `email` varchar(40) NOT NULL,
  `username` varchar(20) NOT NULL,
  `password` varchar(100) NOT NULL,
  `gender` enum('M','F') DEFAULT NULL,
  `address` text
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `account`
--

INSERT INTO `Account` (`firstname`, `lastname`, `email`, `username`, `password`, `gender`, `address`) VALUES
('admin', 'admin', 'admin@hnmdb.com', 'admin', '$2y$10$r/iG.MxtzcMzzIdhoWYGLebJZHq6Ot/smdS49pz/mcnFmVpvFqw6y', 'M', 'Harry &amp; Mione Subang 57000 Kuala Lumpur Selangor'),
('Chun', 'Ho', 'engchunho90@gmail.com', 'baladuki', '$2y$10$P9TBFJwR.LyRlyIRLrSbi.LdZCPVBbZugDUsgFOKGzVWO1tXc4vjy', 'M', 'Dunno SS15 30000 Subang Jaya Selangor'),
('Alvin', 'Cheah', 'firemon4@hotmail.com', 'firemon4', '$2y$10$fIP.FWIAgHWkya7LW/mR2eos9sW6IDqkEMJA0Ry/SH/6hLqJSurcW', 'M', 'SMR Subang 48300 KL Selangor'),
('Hao', 'Yin', 'haoyinisgay@gmail.my', 'haoyinisgay', '$2y$10$m/pEFDNg3YJrqsd8q16dye0eZudaqDBU0GveqcKQsvpbsmrevnB/W', 'M', 'Lagoon View Subang 34566 KL Selangor'),
('Yung', 'Jien', 'yungjien1116@gmail.com', 'yungjien1116', '$2y$10$wSQy0oib5wPx/M0a6Alpq.jRSS65Yso1BSkcTtOsJa2h6W5ZsGSVO', 'M', 'SMR Subang 47500 KL Selangor');

-- --------------------------------------------------------

--
-- Table structure for table `Products`
--

CREATE TABLE `Products` (
  `productID` varchar(20) NOT NULL,
  `productName` varchar(100) NOT NULL,
  `productBrand` varchar(50) NOT NULL,
  `category` varchar(30) NOT NULL,
  `subcategory` varchar(30) NOT NULL,
  `price` float NOT NULL,
  `productDesc` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `Products`
--

INSERT INTO `Products` (`productID`, `productName`, `productBrand`, `category`, `subcategory`, `price`, `productDesc`) VALUES
('P001', 'BACKSTAGE Face & Body Foundation', 'DIOR', 'Makeup', 'Face', 119.99, 'What it is:\r\nA foundation for the face and body in 40 shades with a natural, matte finish and medium, buildable coverage that\'s waterproof and sweat-resistant.\r\n\r\nWhat it does:\r\nDior Backstage Face and Body Foundation is the Dior makeup artistsí secret weapon to create a flawless, runway-ready complexion for both the face and body. This waterproof formula fuses with skin, resisting extreme conditions like workout sessions, water, and even high temperatures and humid environments. It can also be used to camouflage minor imperfections on the neck, shoulders, legs, or anywhere else. Best of all, it ís available in 40 shades with a natural, matte finish.'),
('P002', 'Natural Radiant Longwear Foundation', 'NARS', 'Makeup', 'Face', 199.99, 'What it is:\r\nA foundation with medium buildable coverage, up to 16 hours of lightweight, natural, fade-resistant wear, featuring full-powered radiance to smooth the look of skin.\r\n\r\nWhat it does:\r\nNARSí first 16-hour foundation has a lightweight, breathable, fade-resistant formula and features medium-to-full, buildable coverage in 33 skin-matching shades to fit all skin tones and undertones. The transfer-resistant, sweat-resistant formula stays color-true all day, and continues to look fresh and vibrant, as if it was just applied. This formula features superior blendability for an imperceptible effect that looks natural, like skin. It doesnít look or feel cakey, heavy, drying, or masking. A unique combination of translucent base with micronized amino acid-coated pigments and mineral tone-balancing powders mimic skinís tone, fusing with it for the closest match. NARSí Skin Optimizing Complexóa blend of raspberry, apple, and watermelon extractsóhelps support skinís elastic fibers to smooth and improve skinís appearance over time for optimal radiance.'),
('P003', 'Teint Idole Ultra Long Wear Foundat', 'LANC‘ME', 'Makeup', 'Face', 169.99, 'What it is: \r\nAn oil-free, long-wearing, liquid foundation that delivers medium-to-full coverage and leaves a natural-looking, velvety-matte finish for up to 24 hours. \r\n\r\nWhat it does: \r\nFor those long days, this foundation gives you the full coverage, comfortable, long wear that you need. Not thick or greasy, this foundation\'s innovative formula gives all skin tones flawless, complexion-perfecting coverage, while the broad spectrum SPF 15 sunscreen protects. Redness, pores, and imperfections visibly disappear, evening the skin tone and leaving a mattified-yet-natural result. Formulated with color-true NAI pigments, it maintains your skinís pH level so that color stays put all day longómeaning your makeup doesnít need to be re-touched and provides transfer-resistant coverageóplus, itís infused with perlite and silica, absorbing oil for a shine-free wear.'),
('P004', 'Shameless Youthful-Look 24H Foundat', 'MARC JACOBS BEAUTY', 'Makeup', 'Face', 199.99, 'What it is:\r\nAn innovative, medium, buildable foundation with 24-hour wear and first-to-market, flashback-free SPF 25 for a youthful look.\r\n\r\nWhat does:\r\nHave it all with Shameless Youthful-Look 24H Foundation. Inspired by Marcís very own shameless attitudeóand his tattooóthis innovative foundation lets your best self show all day long. Itís clinically tested for 24-hours of long-wear, and contains a first-to-market technology that encapsulates the SPF in pigment. This innovation makes the SPF visibly undetectable, so thereís no flashback in photos and no ashy, grey undertones in the formula. \r\n\r\nThis oil-free, weightless foundation provides buildable, medium coverage that blends seamlessly. The patented Infinity Millingô process produces super-fine pigments that result in the most natural-looking, self-setting finish. The broad shade range was developed with artists and models worldwide to fit all skin tones and skin types. The perfect level of coverage allows for flexibility across the shade rangeógo deeper or lighter depending on your desired look. \r\n\r\nShameless liquid foundation also beautifies from the inside out with skincare benefits, including phenomenal hydration. It contains snow mushroom, which is known for its impressive ability to hold onto wateróitís like natureís dupe for hyaluronic acid. The formula also contains blue daisy extract, known to visibly diminish the complexion-dulling effects of pollution. Together, they help your skin look hydrated, plumped, and more youthful. Go ahead, show off your skin shamelessly.'),
('P005', 'Ultra HD Perfector Skin Tint Foundation SPF 25', 'MAKE UP FOR EVER', 'Makeup', 'Face', 139.99, 'What it is:\r\nA revolutionary skin tint that blurs and enhances the look of skin for a perfected complexion. \r\n\r\nWhat it does:\r\nThis innovative, weightless formula creates a blurring effect that enhances and perfects the look of skin. Whether youíre new to foundation or an enthusiast seeking a fresh alternative, this sheer-to-medium coverage tint flatters every face. Featuring warming pigments for a subtle, sunkissed glow and protective SP5 25, this formula keeps skin feeling supple and protected. Ultra HD Perfector breaks all of the limits weíve come to expect from foundations with a texture thatís effortless to apply with your fingertips, a nurturing formula, and a long-lasting natural finish. This is your most natural, perfected skin, on demand. \r\n\r\nUltra HD Perfector is available in 10 shades, with each individual shade spanning uniquely across multiple skin tones.\r\n'),
('P006', 'Radiant Creamy Concealer', 'NARS', 'Makeup', 'Face', 24.99, 'What it is: \r\nAn award-winning concealer that provides medium-to-full, buildable coverage and corrects, contours, highlights, and perfects. \r\n\r\nWhat it does: \r\nIdeal for all skin types, Radiant Creamy Concealer is a multi-action formula that instantly masks imperfections, blurs the look of lines and wrinkles, and hides dark circles and signs of fatigue. The botanical blend hydrates, firms, reduces redness, and strengthens the look of skin by helping its barrier retain moisture. Light-diffusing technology evens out the complexion so that skin appears fresh and natural with a radiant finish. It also delivers antioxidant protection to help shield skin against damaging free radicals. \r\n\r\nThe Mineral Tone Balancing Powder works to optically correct, not mask, imperfections. Unique powders even the skintone and provide invisible skin correction so skin that skin appears radiant, fresh, and natural. Itís infused with a Multi-Active Botanical Blend, which is loaded with magnolia bark extract, grape seed extract, and vitamin E to help hydrate, reduce the appearance of redness, and improve skin resilience by promoting moisture retention. Light-Diffusing Mineral Powder reduces the appearance of fine lines and wrinkles and helps even out skintone.'),
('P007', 'Creaseless Under Eye Concealer ', 'TARTE', 'Makeup', 'Face', 99.99, 'What it is:\r\nA vegan, full-coverage, creamy skincare concealer, now with 30 shades and a new applicator thatís totally foolproofóitís the same formula you love, but in new packaging.\r\n\r\nWhat it does:\r\nCreaseless Concealer completely covers dark circles, hyperpigmentation, redness, pimples, tattoos. The waterproof formula doesnít crease or sit in fine lines. Itís also powered by vitamin-C-rich maracuja for brighter, firmer-looking, and smoother-looking skin.'),
('P008', 'Killawatt Freestyle Highlighter', 'FENTY BEAUTY BY RIHA', 'Makeup', 'Face', 129.99, 'What it is:\r\nA line of weightless, long-wear cream-to-powder hybrid highlighters in solos and expertly paired duos. \r\n\r\nWhat it does:\r\nLight up where you want, when you want. Killawatt Freestyle Highlighter was born to reflect your every mood with its lineup of luminizing solos and duos. With a dose of skin-glorifying color, Killawatt ranges from subtle dayglow to insanely supercharged shades that were designed for all skin tones. \r\n\r\nUnlike your everyday highlighter, Killawatt keeps skin lit beyond sundown with its weightless long-wear formulaóa cream-powder hybrid that instantly melts into skin and blends with almost zero effort. Another win: Itís loaded with superfine shimmer for an ultra-smooth, creamy texture. \r\n\r\nFor killer radiance, Killawattís your go-to for highlighting your face, eyes, lips, collarboneÖ.literally anywhere you crave a touch of light.'),
('P009', 'Shimmering Skin Perfector Pressed Highlighter', 'BECCA', 'Makeup', 'Face', 179.99, 'What it is:\r\nAn award-winning highlighting powder with an ultra-buttery texture that melts into skin for the ultimate high-impact glow. \r\n\r\nWhat it does:\r\nThis enhanced lineup of BECCAís iconic highlighter features an unparalleled shade range that caters to all skin tones. \r\n\r\nThis one-of-a-kind formula is enriched with ultra-fine, multitoned, luminescent pearls that adjust to your skinís undertones and amplify your natural radiance. Unlike traditional pressed powders, this unique formula blends pigments with liquids, creating a creamy feel that applies seamlessly and never cakes. Inspired by the dazzling light of the midday sun, the result is a high-impact, elegant finish that doesnít look glittery. \r\n'),
('P010', 'Translucent Loose Setting Powder ', 'LAURA MERCIER', 'Makeup', 'Face', 139.99, 'What it is: \r\nA cult-favorite and award-winning, silky powder with a touch of sheer coverage to set makeup for lasting wear. \r\n\r\nWhat it does: \r\nTranslucent Loose Setting Powder locks in makeup for long-lasting wear, without adding weight or texture. This bestseller creates a modern, matte finish with a touch of sheer coverage, while it absorbs oil and reduces shine all day. The pros know why it\'s their favorite: the powder is a little denser than an average powder, providing super smooth, even application and blending. This no-flashback formula means you\'ll look great in photos, and it creates a soft-focus effect to subtly blur the look of fine lines and imperfections. It will not settle into fine lines or pores and never looks cakey. These truly translucent shades work on all skin tonesófrom the fairest to the deepest. The just-released, Translucent Medium Deep shade was designed to be completely translucent on medium-deep to the deepest skin tones, ensuring that every skin tone gets a perfectly flawless, translucent finish. \r\n\r\nTranslucent: perfect for fair to medium and tan skin tones. \r\nTranslucent Medium Deep: Ideal for medium-deep to the deepest skin tones.\r\n'),
('P011', 'Eyeshadow Palette 28', 'NATASHA DENONA', 'Makeup', 'Eyes', 799.99, 'What it is: \r\nAn eyeshadow palette with 28 shades that beautifully layer together for breathtaking eye looks. \r\n\r\nWhat it does: \r\nNatasha Denonaís Eyeshadow Palette 28 is ultra-pigmented, blends like a dream, and is long lasting. Enriched with moisturizing ingredients, itís made with real crushed pearls that create a radiant glow. The palette features an array of ultra-pigmented, unique shades and finishes. The revolutionary formula is smooth to the touch so that eye color glides seamlessly onto your lids while providing vivid color payoff with a silky-soft feel.'),
('P012', 'Soft Glam Eyeshadow Palette', 'ANASTASIA BEVERLY HILLS ', 'Makeup', 'Eyes', 259.99, 'What it is:\r\nAn everyday to night palette with 14 shades, including essential mattes and glam shimmer finishes.\r\n\r\nWhat it does:\r\nThis palette features 14 shades in ultra-matte, duo chrome, and metallic finishes that let you create softly-glamorous looks any time. Each shade is fully-pigmented and easy to blend. The palette is luxuriously packaged, with a large mirror and double-ended brush.\r\n'),
('P013', 'Better Than Sex Mascara', 'TOO FACED', 'Makeup', 'Eyes', 64.99, 'What it is:\r\nAn intensely black, volumizing mascara with an hourglass-shaped brush that separates, coats, and curls each lash to voluptuous perfection.\r\n\r\nWhat it does:\r\nInspired by the curves of a womanís body, the hourglass-shaped brush was designed with extra stiff bristles to maximize the performance of this carbon black, collagen-fueled formula. One coat and lashes are full and defined. Two coats and lashes are even more luscious, curled, and dramatic. Three coats help you achieve the most intense, black, multidimensional lashes possible.'),
('P014', 'Diorshow Mascara', 'DIOR', 'Makeup', 'Eyes', 126.99, 'What it is:\r\nA bestselling mascara, now with a conditioning formula thatís enriched with microfibers for a lash extension effect.\r\n\r\nWhat it does:\r\nThe reinvented Diorshow Mascara features Diorís revolutionary patented AIR-LOCKô wiping system that keeps mascara fresh until the last useóas though you were using it on day one. Its original XXL Brush, a backstage makeup pro-inspired tool, is perfect for applying the versatile, microfiber-enhanced formula that gives buildable volume with each stroke. The formula\'s lash-care action helps smooth lashes for even more spectacular shape, coverage, and volume. With Dior\'s delicate signature rose essence, Diorshow Mascara elevates your lashes and your senses. Get fuller lashes, bolder impact, and a formula that lasts with this conditioning mascara.'),
('P015', 'Tattoo Liner', 'KAT VON D', 'Makeup', 'Eyes', 79.99, 'What it is:\r\nA liquid eyeliner with an innovative brush tip for effortless, precise application. \r\n\r\nWhat it does:\r\nAchieve eye perfection with this high-pigment, waterproof liner that stays put all day for a fade-, melt-, crack-, and run-resistant finish. The superfine and flexible brush tip glides across the lashline for incredibly fluid application, allowing you to create a variety of looks with ease. Unlike traditional felt tip liners, this brush tip will not fray.'),
('P016', 'Stay All Day Waterproof Liquid Eye Liner', 'STILA', 'Makeup', 'Eyes', 79.99, 'What it is:\r\nAn easy-application, waterproof liquid liner that stays on all day and night.\r\n\r\nWhat it does:\r\nThis easy-glide, quick-dry precision liner stays in place until you say whenóno smudges, feathering, or running. The thin, marker-like tip is easy to use, even for the beauty beginner, and delivers any lookófrom a thin line to a bold, dramatic stroke. It goes on smoothly without skipping, smudging, or pulling, and lasts all day.'),
('P017', 'CILS BOOSTER XL Super-Enhancing Mascara Base', 'LANC‘ME', 'Makeup', 'Eyes', 99.99, 'What it is:\r\nA lash-conditioning, mascara primer in the same great formula and new packaging that conditions and primes lashes to maximize resultsócreating even longer and more volumized lashes. \r\n\r\nWhat it does:\r\nGive your lashes an XL boost. With just one sweep, this innovative mascara primer glides on and evenly coats and smooths your lashes to maximize the results of your favorite mascara. The magic behind this mascara base is the conditioning formulaóinfused with micro-fibers and Vitamin Eó which adds extra length and thickness to lashes for added visible performance. White in color, it allows the black pigments to stand out from the clean base with more intensity than with traditional mascaras.'),
('P018', 'Eye Basics', 'LAURA MERCIER', 'Makeup', 'Eyes', 114.99, 'What it is:\r\nA water-resistant eyelid primer that camouflages imperfections and discolorations, while it enhances the durability of eye makeup. \r\n\r\nWhat it does:\r\nEye Basics provides the perfect canvas for eyelids to help eye color stay on longer. The highly versatile formula is water-resistant and crease-proof. Its sheer, creamy texture blends easily and smoothly, leaving a long-lasting, semi-matte finish.\r\n'),
('P019', 'Confession Lipstick Archive', 'HOURGLASS', 'Makeup', 'Lips', 2499.99, 'What it is:\r\nA limited-edition collectorís set of 30 Confession Ultra Slim Lipstick Refills paired with two sleek gold applicators to be used interchangeably with all Confession Refills. \r\n\r\nWhat it does:\r\nUltra Slim Lipstick delivers creamy, saturated, long-wearing color with a satin finish without smudging or feathering. Each ultra slim lipstick is designed to be used with the sleek gold applicators to provide the ultimate control to precisely accentuate, contour, and define the lips. The two gold applicators can be used interchangeably with the full collection of Confession Ultra Slim Lipstick Refills.'),
('P020', 'Amuse Bouche Lipstick', 'BITE BEAUTY', 'Makeup', 'Lips', 99.99, 'What it is: \r\nA collection of high-impact lipsticks in dimensional shades that have been handcrafted to deliver extreme moisture, soft texture, and creamy wear. \r\n\r\nWhat it does: \r\nSwipe on bold, creamy lip color with Bite Beautyís Amuse Bouche. Created and crafted by hand, Biteís small batch, low-heat process preserves a balanced blend of lip-quenching nutrients, vitamins, and omega oils that are essential for achieving healthy-looking lips. Made with 12 edible oils and triple milled pigments, this lipstick provides saturated lip color with weightless coverage and a citrus flavor made from fresh pressed fruit. '),
('P021', 'Lip Lacquer', 'TOM FORD', 'Makeup', 'Lips', 199.99, 'What it is:\r\nA lip lacquer that delivers pure, long-wearing color in three decadent formulas.\r\n\r\nWhat it does:\r\nTom Ford Lip Lacquer delivers pure, unadulterated liquid lip color in three decadent formulasóLiquid Matte, Liquid Metal, and Liquid Patent. Drenched in long-wearing, stay-true color, lips delight in the lightweight, comfortable textures infused with smoothing moisturizers.\r\n\r\nLiquid Patent formulas combine a lip stain with an ultra-glossy finish. Intense, vibrant shades evoke the transfixing look of skin-tight vinyl.\r\n\r\nLiquid Metal is an innovative liquid-gel with optical plumping effects. Pure metallic color with mirror-like dimension glides on with lustrous impact.\r\n\r\nLiquid Matte is rich and creamy upon application. The luxe formula transforms into feather-light, concentrated color in a fade-resistant, full-coverage, velvet matte finish.'),
('P022', 'Prime + Color Lip Gloss', 'TRÈSTIQUE', 'Makeup', 'Lips', 99.99, 'What it is:\r\nA two-in-one lip duo with primer and color for perfectly smooth, vibrant lip color that wears all day. \r\n\r\nWhat it does:\r\nSide one is an ultra-moisturizing lip primer that smooths and preps lips, creating the perfect canvas for color. The primer is infused with light-perfecting powders for a smoothing, soft focus effect. \r\n\r\nSide two is a color glaze. It glides on with a balmy feel and leaves lips with a soft shine and lasting stain. Lip Glaze is infused with coconut oil, which is known for its hydrating properties.'),
('P023', 'Gloss Bomb Universal Lip Luminizer ', 'FENTY BEAUTY BY RIHANNA', 'Makeup', 'Lips', 83.99, 'What it is: \r\nAn ultimate, gotta-have-it lip gloss with explosive shine that feels as good as it looksóin one universal rose nude shade. \r\n\r\nWhat it does: \r\nThis stop-everything, give-it-to-me gloss delivers explosive shine in one perfect rose nude shade handpicked by Rihanna herself: Fenty Glow. Weíre talking the unicorn of nudes that looks good on everyone. \r\n\r\nOne luscious swipe of Gloss Bombís XXL wand gives lips more to love, while conditioning shea butter enriches from within. Lips look instantly fuller and smoother. It feels amazing on your lipsówith a non-sticky formula thatís super shinyóand has an addictive peach-vanilla scent you just canít get enough of.\r\n'),
('P024', 'Enamored Hi-Shine Lip Lacquer Lipgloss', 'MARC JACOBS BEAUTY', 'Makeup', 'Lips', 104.99, 'What it is: \r\nA high-shine lip gloss in covetable shades with lasting brilliance. \r\n\r\nWhat it does: \r\nEnamored Hi-Shine Lip Lacquer lip gloss delivers maximum color and brilliance with its unique Triple Shine Complex, a blend of high-performance ingredients that provide unstoppable wear and shine like \"30 coats of lacquer.\" The brilliant shine contributes to an optical plumping look. And, Enamored feels cushiony on the lips, never sticky. This mint-scented lip gloss collection features a profusion of creamy pinks, shimmering lavenders, and iridescent brights that give lips a lush look with lasting color and unbelievable shine.'),
('P025', 'Velvet Matte Lipstick Pencil ', 'NARS', 'Makeup', 'Lips', 132.99, 'What it is:	\r\nA cult-favorite, matte lip pencil that instantly delivers the impact of a matte lipstick with the spontaneity of a pencil. \r\n\r\nWhat it does: \r\nThe NARS Velvet Pencil ensures that lips are instantly saturated with rich, vivid pigments and a velvety matte finish. Its jumbo size provides the application of a lipstick with the convenience of an artist pencil, and the tapered end is perfect for lining, defining, and filling in lips. Its non-drying formula is enriched with vitamin E and emollients for a creamy texture, while a blend of unique silicones ensures long-lasting, seamless matte color for hours. Just pair it with another lip product for added dimension or as a tinted base. Whether itís soft and neutral or bold and edgy, this lip pencil is ideal for making a lip statement. '),
('P026', 'Poutliner Longwear Lip Liner Pencil', 'MARC JACOBS BEAUTY', 'Makeup', 'Lips', 102.99, 'What it is:\r\nA collagen-infused, long-wear gel lip liner pencil. \r\n\r\nWhat it does:\r\nThese gel-based, barely-there colors luxuriously line, define, and shape your lips, creating the perfect lasting canvas for lip color. Designed to work seamlessly with the full spectrum of Le Marc and New Nudes shades, these lip liners complement every lip coloróno matter how light, bright, or bold. Formulated with collagen to help fill in lines and prevent bleeding, this cream gel formula glides on flawlessly for all-day wear. '),
('P027', 'Full-On Lip Polish', 'BUXOM ', 'Makeup', 'Lips', 79.99, 'What it is:\r\nA bestselling gloss from the lip-plumping authority in a tingly, shimmer-sheer finishónow available in holographic, prismatic top coat shades.\r\n\r\nWhat it does:\r\nThis high-shine gloss tingles to coax a gorgeous lip look while pampering and moisturizing lips with vitamins A and E. Lips stay lusciously soft and seriously sexy. Layer on the love and take your look to the next level with new holographic top coats, which feature a unique silicone applicator. Full-On Lip Polish is also now available in prismatic special-effect pearl finishes.'),
('P028', 'Dior Addict Lacquer Plump', 'DIOR', 'Makeup', 'Lips', 129.99, 'What it is:\r\nA lip-plumping lacquered ink that provides intense, long-wear color and an incredibly comfortable texture.\r\n\r\nWhat it does:\r\nDior has pushed the boundaries of lip lacquer with the creation of their first lip-plumping lacquered ink. Like an ink, the lacquer dries down for a deeper saturation of color. It also tints the lips for up to eight hours.* A plumping effect delivers a more voluminous lip look and shaping effect, along with unprecedented hydration. Lips experience up to 78 percent increased moisture levels** for up to 24 hours after application.\r\n\r\nIts secret? An oil-in-water emulsion infused with pigments and hibiscus extract for a volumizing effect, paired with hyaluronic acid for rich hydration.'),
('P029', 'Orgasm Afterglow Lip Balm', 'NARS', 'Makeup', 'Lips', 106.99, 'What it is:\r\nA hydrating lip balm with a subtle hint of Orgasm color and a radiant finish.\r\n\r\nWhat it does:\r\nAfterglow Lip Balm delivers a sheer wash of the universally-flattering Orgasm shade with a radiant finish. The formula features NARSís MonoÔ Hydrating Complex for smooth, supple comfort. Itís also infused with a blend of antioxidant ingredients to help protect lips.'),
('P030', 'Ultimate Revival Cream', 'SK-II', 'Skincare', 'Moisturizer', 189.99, 'What it is:\r\nA rich, luxurious facial cream that works to enhance skin’s vitality and structure. \r\n\r\nWhat it is formulated to do:\r\nThis luxurious, incredibly powerful facial cream utilizes a combination of 15 ingredients blended together in a cutting-edge formula to enhance skin’s vitality and structure. It strengthens skin’s moisture barrier to maintain the skin over time.'),
('P031', 'ABSOLUE PREMIUM Bx - Absolute Night Recovery Cream', 'LANCÔME', 'Skincare', 'Moisturizer', 799.99, 'What it is: \r\nA nighttime replenishment that combines three advanced discoveries in one rich and soothing cream. \r\n\r\nWhat it is formulated to do: \r\nAge and hormonal changes are known to weaken skin at the structural level, leaving it dry, less elastic, and dull. Even a full night\'s sleep does not provide optimal recovery. With Absolue Night Premium ßx, Lancôme revolutionizes nighttime replenishment by combining three advanced discoveries in one rich and soothing cream. Pro-Xylane™, an exceptional and precise patented molecule that restores essential moisture so skin retains the appearance of youthful substance, firmness, and radiance—as if signs of aging are visibly repaired. The intensely replenishing ßio-Network™ complex—a blend of wild yam, soy, sea algae, and barley—helps enhance performance for visible rejuvenation. N-Stimuline™ helps support the natural recovery process so skin wakes up looking well-rested and luminous.'),
('P032', 'Lala Retro Whipped Cream', 'DRUNK ELEPHANT', 'Skincare', 'Moisturizer', 239.99, 'Which skin type is it good for?\r\nNormal\r\nOily\r\nCombination\r\nDry\r\nSensitive \r\n\r\nWhat it is:\r\nA retro-style moisturizer that rescues dry, dull skin while slowly delivering a steady dose of barrier moisture throughout the day and night.'),
('P033', 'Benefiance WrinkleResist24 Night Cream', 'SHISEIDO', 'Skincare', 'Moisturizer', 249.99, 'What it is:\r\nAn ultra-rich formula that helps improve visible signs of premature aging. \r\n\r\nWhich skin type is it good for?\r\nNormal\r\nDry \r\n'),
('P034', '100 percent Pure Argan Oil', 'JOSIE MARAN ', 'Skincare', 'Moisturizer', 99.99, 'What it is:\r\nA clinically proven 100 percent organic, do-it-all essential that naturally moisturizes and smooths fine lines and wrinkles to preserves skin\'s youthful radiance. \r\n\r\nWhich skin type is it good for?\r\n\r\nOily\r\nDry\r\nSensitive\r\n'),
('P035', 'Facial Treatment Essence ', 'SK-II', 'Skincare', 'Cleanser', 109.99, 'What it is:\r\nAn iconic essence with over 90 percent pitera.	\r\n\r\nWhich skin type is it good for?\r\nNormal\r\nOily\r\nCombination\r\nDry\r\nSensitive\r\n'),
('P036', 'Take The Day Off Cleansing Balm', 'CLINIQUE', 'Skincare', 'Cleanser', 119.99, 'What it is:\r\nA transformational, lightweight makeup remover that goes from balm to oil to milk to melt away every trace of eye and face makeup and sunscreen. \r\n\r\nWhich skin type is it good for?\r\nNormal\r\nOily\r\nCombination\r\nDry\r\nSensitive'),
('P037', 'Bi-Facil Double-Action Eye Makeup Remover', 'LANCÔME ', 'Skincare', 'Cleanser', 109.99, 'What it is:\r\nAn award-winning, gentle, liquid eye makeup remover. \r\n\r\nWhat it is formulated to do:\r\nThis formula activates when shaken to gently whisk away even waterproof eye makeup while conditioning and refreshing the skin. Ideal for sensitive skin and contact lenses, it leaves eyes feeling cool and relaxed without an oily residue.\r\n'),
('P038', 'Bye Bye Makeup 3-in-1 Makeup Melting Cleansing Ba', 'IT COSMETICS', 'Skincare', 'Cleanser', 155.99, 'What it is:\r\nA revolutionary, three-in-one cleanser, purifying makeup remover, and antiaging serum for better looking skin.\r\n\r\nWhich skin type is it good for?\r\nNormal\r\nOily\r\nCombination\r\nDry\r\nSensitive\r\n'),
('P039', 'Facial Treatment Clear Lotion Toner\r\n', 'SK-II', 'Skincare', 'Cleanser', 289.99, 'What it is:\r\nA hydrating toner to complete your cleansing ritual. \r\n\r\nWhich skin type is it good for?\r\nNormal\r\nOily\r\nCombination\r\nDry\r\nSensitive'),
('P040', 'Calendula Herbal Extract Alcohol Free Toner', 'KIEHL\'S SINCE 1851', 'Skincare', 'Cleanser', 199.99, 'What it is:\r\nAn effective, alcohol-free facial toner.\r\n\r\nWhich skin type is it good for?\r\nNormal\r\nOily '),
('P041', 'Ultimune Power Infusing Concentrate', 'SHISEIDO', 'Skincare', 'Treatment', 199.99, 'What it is:\r\nA one-of-a-kind boosting pre-treatment that helps defend against multiple signs of aging and damage, while enhancing the effects of skincare that follows. \r\n\r\nWhich skin type is it good for?\r\nNormal\r\nOily\r\nCombination\r\nDry\r\nSensitive\r\n'),
('P042', 'D-Bronzi Anti-Pollution Sunshine Serum', 'DRUNK ELEPHANT', 'Skincare', 'Treatment', 149.99, 'What it is: \r\nA serum that immediately replenishes the delicate balance that supports a healthy barrier function of skin—like sunshine’s bronzy color, delivered without the damage.\r\n\r\nWhich skin type is it good for? \r\nNormal \r\nOily \r\nCombination \r\nDry \r\nSensitive '),
('P043', 'T.L.C. Sukari Babyfacial™', 'DRUNK ELEPHANT', 'Skincare', 'Treatment', 319.99, 'What it is: \r\nA pro-quality AHA/BHA mask that works as a \"facial\" to reveal greater clarity, improved skin texture and tone, and a more youthful-looking radiance. \r\n\r\nWhich skin type is it good for? \r\nNormal \r\nOily \r\nCombination \r\nDry \r\nSensitive '),
('P044', 'No.04 Bois de Balincourt Perfume Oil', 'MAISON LOUIS MARIE', 'Fragrance', 'Clean', 227.99, 'Maison Louis Marie composes delicate scents to enchant your lifestyle with a botanical tradition since 1792. This scent is a sandalwood fragrance with a dominant cedarwood and sandalwood accord supplemented by a spicy cinnamon nutmeg complex and an earthy vetiver note.\r\n'),
('P045', 'Myth Gift Set: A Brooklyn Story', 'ELLIS BROOKLYN', 'Fragrance', 'Clean', 449.99, 'Ellis Brooklyn bestseller Myth Eau de Parfum and Excellent Body Milk now come in one cool, reusable holographic clutch. Myth is an artfully synthesized blend of soft ambrette seeds and earthy white cedarwood intertwined with delicate jasmine petals and pink lotus. It\'s a sensual scent worthy of the gods.'),
('P046', 'Myth Eau de Parfum', 'ELLIS BROOKLYN ', 'Fragrance', 'Clean', 199.99, 'The airy beauty of jasmine petals and tiger orchid meet the sexy, undeniable warmth of liquid musks and white cedarwood. It\'s a sophisticated fragrance for the senses, worthy of the myths it will create. \r\n\r\n\"I specifically created Myth myselfóa modern musk that\'s still feminine and invitingóand it\'s what I wear every day.\"óBee Shapiro, Brand Founder \r\n\r\nEllis Brooklyn fragrances are created with the environment in mind from the packaging and formula to the final productóthe definition of luxury for a new generation. '),
('P047', 'Costa Azzurra', 'TOM FORD', 'Fragrance', 'Women', 599.99, 'Private blend Costa Azzurra captures the evocative mix of fragrant woods on the Mediterranean island of Sardinia. Its unique aroma of salty beaches, dry herbs, evergreen trees, and driftwood mingles with scents of the low, thickly forested landscape known as the Macchia—a tangle of oaks, juniper pines, and herbs. \r\n'),
('P048', 'L’Atelier de Givenchy Chypre Caresse', 'GIVENCHY', 'Fragrance', 'Women', 834.99, 'L\'Atelier de Givenchy Chypre Caresse is a delicate and timeless fresh chypre fragrance for a romantic and evanescent allure. Experience a delicate and timeless, fresh chypre fragrance that melds lemon pulp, the herbal accent of angelica, and the woody temperament of patchouli. The fragrance is encased in a beautiful glass bottle, with colorful thread around the neck of the cap. '),
('P049', 'Beach Walk Rollerball', 'MAISON MARGIELA', 'Fragrance', 'Women', 119.99, 'Beach Walk combines fresh and radiant notes of bergamot, coconut milk, lemon, pink pepper, and musk to evoke a familiar but forgotten moment—a walk along a sandy beach. \r\n\r\nClose your eyes and let the fragrance transport you to the memory of an afternoon stroll along the ocean. Your feet sink into the wet sand as waves brush against your skin. The sun sinks gently through the crystal sky, its warmth balanced by a soft breeze with the subtle tangy scent of water. Beach Walk evokes hints of ocean spray, and captures the carefree bliss of a summer day. '),
('P050', 'La Vie Est Belle Rollerball', 'LANCÔME ', 'Fragrance', 'Women', 89.99, 'La Vie Est Belle, French for \"life is beautiful\", represents a choice—the choice to create your own path to happiness. Made with the most precious natural ingredients, the fragrance entwines the elegance of iris with the strength of patchouli and the sweetness of praline. Floral notes of sambac, jasmine and Tunisian orange blossom are added in the form of sublime absolutes. \r\n\r\nLa Vie Est Belle is the fragrance of joyful femininity that makes life more beautiful. It is for the woman who lives in the present, who is filled with honesty, truth, and gratitude, and who is free of social constraint, to blaze her own unique path. \r\n'),
('P051', 'COCO MADEMOISELLE Moisturizing Body Lotion', 'CHANEL', 'Fragrance', 'Women', 255.99, 'Lightweight moisturizing lotion luxuriously perfumed with the feminine and sexy, young and exciting scent softens and silkens skin.'),
('P052', 'Amazing Grace Firming Body Emulsion', 'PHILOSOPHY', 'Fragrance', 'Women', 179.99, 'A luxurious, firming moisturizer infused with the bestselling Amazing Grace fragrance to purify, hydrate, and revitalize. '),
('P053', 'Bronze Goddess Eau Fraiche Skinscent', 'ESTÉE LAUDER', 'Fragrance', 'Women', 299.99, 'Feel the heat. The original, alluring Eau Fraîche you know and love has returned for another Spring/Summer season. The spray imparts a sensuous, sun-drenched blend of bergamot, warm amber, tiare flower, and vanilla—blended with delicious, creamy coconut. Reminiscent of a sun-drenched beach, this exotic scent unveils the creamy heart of golden amber that emanates pure summer. '),
('P054', 'Alien Hair Mist', 'MUGLER', 'Fragrance', 'Women', 159.99, 'What it is:\r\nA luxurious hair mist to pamper and infuse your hair with the radiant scent of Alien.'),
('P055', 'Bloom Hair Mist', 'GUCCI', 'Fragrance', 'Women', 179.99, 'A hair mist featuring the original scent’s trio of white flowers sambac jasmine, tuberose, and Rangoon creeper.'),
('P056', 'COCO MADEMOISELLE Foaming Shower Gel', 'CHANEL', 'Fragrance', 'Women', 249.99, 'Moisturizing and cleansing gel leaves skin lightly fragranced with the feminine and sexy, young and exciting scent. Produces a rich, creamy foam that cleanses the skin gently, turning the bath or shower into a refreshing, relaxing environment.\r\n'),
('P057', 'Almond Coconut Honey Bath', 'LAURA MERCIER', 'Fragrance', 'Women', 179.99, 'A foaming, honey-scented moisture bath.This decadent, fragrant bath leaves skin feeling clean, fresh, and moisturized. Inspired by Laura Mercier’s French upbringing, the Almond Coconut Body & Bath Collection features playful yet sophisticated formulas inspired by the aura and aroma of the French pâtisserie.'),
('P058', 'CHANCE EAU FRAÎCHE Foaming Shower Gel', 'CHANEL', 'Fragrance', 'Women', 222.99, 'Garnering one of the fragrance industry\'s most prestigious honors — a 2010 FiFi Award finalist nomination — this luxurious bath essential instantly elevates one\'s daily bathing ritual. Its soft, fresh texture transforms into a light foam that caresses the skin with the delicate and sparkling notes of CHANCE EAU FRAÎCHE.\r\n'),
('P059', 'Restore Shampoo', 'LIVING PROOF', 'Hair', 'Shampoo & Conditioner', 56, 'What it is: \r\nA shampoo that’s the first step to making dry, damaged hair feel and look visibly healthier.\r\n\r\nWhich hair type is it good for? \r\nStraight \r\nWavy \r\nCurly \r\nCoiled \r\nTightly Coiled '),
('P060', 'Hydrating Shampoo', 'MOROCCANOIL', 'Hair', 'Shampoo & Conditioner', 87.99, 'What it is: \r\nA hydrating, daily shampoo that’s infused with antioxidant-rich argan oil and replenishing vitamins to nourished hair. \r\n\r\nWhich hair type is it good for? \r\nStraight \r\nWavy  \r\nCurly \r\nCoiled \r\nTightly Coiled '),
('P061', 'Perfect Hair Day Dry Shampoo', 'LIVING PROOF', 'Hair', 'Shampoo & Conditioner', 103.99, 'What it is:\r\nA dry shampoo that actually cleans hair, eliminating oil, sweat, and odor.\r\n\r\nWhich hair type is it good for?\r\nStraight\r\nWavy\r\nCurly\r\nCoiled\r\nTightly Coiled \r\n'),
('P062', 'Jet Lag Invisible Dry Shampoo', 'IGK ', 'Hair', 'Shampoo & Conditioner', 99.99, 'What it is:\r\nAn invisible, weightless, buildable dry shampoo that uses finely milled volcanic ash for a lightweight cleanse to refresh hair and erase mild dirt and oil. \r\n\r\nWhich hair type is it good for?\r\nStraight\r\nWavy\r\nCurly\r\nCoiled\r\nTightly Coiled\r\n'),
('P063', 'Moisture Repair Conditioner', 'MOROCCANOIL ', 'Hair', 'Shampoo & Conditioner', 99.99, 'What it is: \r\nA moisture-balancing conditioner that gently cleanses and detangles hair while infusing each strand with antioxidant-rich argan oil and other nutrients. \r\n\r\nWhich hair type is it good for? \r\nStraight \r\nWavy \r\nCurly \r\nCoiled \r\nTightly Coiled '),
('P064', 'Hot Girls Hydrating Conditioner', 'IGK', 'Hair', 'Shampoo & Conditioner', 99.99, 'What it is:\r\nA deep moisturizing conditioner that detangles and de-frizzes hair.\r\n\r\nWhich hair type is it good for?\r\nStraight\r\nWavy\r\nCurly\r\nCoiled\r\nTightly Coiled\r\n'),
('P065', 'Beach Club Texture Spray', 'IGK', 'Hair', 'Hair Styling & Treatment', 129.99, 'What it is:\r\nA salt-free texturizing spray that gives you beachy waves and volume without drying out your hair. \r\n\r\nWhich hair type is it good for?\r\nStraight\r\nWavy\r\nCurly\r\nCoiled\r\nTightly Coiled\''),
('P066', 'No Frizz Nourishing Styling Cream', 'LIVING PROOF', 'Hair', 'Hair Styling & Treatment', 157.99, 'What it is: \r\nA styling cream that smooths, conditions, and eliminates frizz by blocking humidity without weighing hair down. \r\n\r\nWhich hair type is it good for? \r\nStraight \r\nWavy \r\nCurly \r\nCoiled \r\nTightly Coiled '),
('P067', 'Flex Shaping Hairspray', 'LIVING PROOF', 'Hair', 'Hair Styling & Treatment', 94.99, 'What it is:\r\nA versatile hairspray to set, style, and finish with workable, brushable, medium hold.\r\n\r\nWhich hair type is it good for?\r\nStraight\r\nWavy\r\nCurly\r\nCoiled\r\nTightly Coiled\r\n'),
('P068', 'Caviar Anti-Aging Working Hair Spray', 'ALTERNA HAIRCARE', 'Hair', 'Hair Styling & Treatment', 119.99, 'What it does:\r\nThis ultra-dry hairspray with progressive control provides humidity resistance with a flexible, yet brushable, light-to-medium hold.\r\n\r\nWhat it is:\r\nAn ultra-dry, brushable hairspray.'),
('P069', '100 percent Pure Argan Oil', 'JOSIE MARAN ', 'Hair ', 'Hair Styling & Treatment', 144.99, 'What it is:\r\nA clinically proven 100 percent organic, do-it-all essential that naturally moisturizes and smooths fine lines and wrinkles to preserves skin\'s youthful radiance. \r\n\r\nWhich skin type is it good for?\r\n\r\nOily\r\nDry\r\nSensitive'),
('P070', 'Mermaid Hair Oil', 'CAPTAIN BLANKENSHIP', 'Hair', 'Hair Styling & Treatment', 134.99, 'What it is:\r\nA hair oil and scalp treatment that adds moisture and shine to hair while combating frizz.\r\n\r\nWhich hair type is it good for?\r\nStraight\r\nWavy\r\nCurly\r\nCoiled\r\nTightly Coiled'),
('P071', 'Restorative Hair Mask', 'MOROCCANOIL', 'Hair', 'Hair Styling & Treatment', 175.99, 'What it is:\r\nA protein-rich, argan oil-infused mask that restores and helps repair dry, weakened hair to improve texture, elasticity, and manageability. \r\n\r\nWhich hair type is it good for?\r\nStraight \r\nWavy\r\nCurly\r\nCoiled\r\nTightly Coiled'),
('P072', 'Expensive Amla Oil Hi-Shine Topcoat', 'IGK', 'Hair', 'Hair Styling & Treatment', 119.99, 'What it is:\r\nAn in-shower protective gloss that adds incredible shine and strength while sealing hair\'s cuticles. \r\n\r\nWhich hair type is it good for?\r\nStraight\r\nWavy\r\nCurly\r\nCoiled\r\nTightly Coiled '),
('P073', 'Call Time Styling Primer', 'IGK', 'Hair', 'Hair Styling & Treatment', 107.99, 'What it is:\r\nA hydrating hair primer infused with coconut water and coconut oil to protect from heat, UV rays, and color fading while keeping hair soft and frizz-free. \r\n\r\nWhich hair type is it good for?\r\nStraight\r\nWavy\r\nCurly\r\nCoiled\r\nTightly Coiled '),
('P074', 'Sold Out Curl Priming Basecoat', 'IGK', 'Hair', 'Hair Styling & Treatment', 114.99, 'What it is:\r\nA nutrient-rich, curl-enhancing hair primer that reduces frizz and adds shine while protecting from heat and color fading.\r\n\r\nWhich hair type is it good for?\r\nWavy\r\nCurly\r\nCoiled\r\nTightly Coiled'),
('P075', 'Scalp Revival Charcoal + Coconut Oil Micro-exfoliating Shampoo', 'BRIOGEO', 'Hair ', 'Hair Styling & Treatment', 169.99, 'What it is:\r\nA unique, charcoal- and coconut oil-infused scalp shampoo that detoxifies, exfoliates, soothes, and balances the scalp for optimal scalp health. \r\n\r\nWhich hair type is it good for?\r\nStraight\r\nWavy\r\nCurly\r\nCoiled\r\nTightly Coiled \r\n'),
('P076', 'Scalp Revival Charcoal + Tea Tree Scalp Treatment', 'BRIOGEO', 'Hair', 'Hair Styling & Treatment', 129.99, 'What it is:\r\nA unique, charcoal-infused scalp treatment that detoxifies, soothes, and balances the scalp for optimal scalp health. \r\n\r\nWhich hair type is it good for?\r\nStraight\r\nWavy\r\nCurly\r\nCoiled\r\nTightly Coiled '),
('P077', 'Future Solution LX Superior Radiance Serum\r\n', 'SHISEIDO', 'Hair', 'Hair Styling & Treatment', 887.99, 'What it is:\r\nA brightening serum to provide a smooth skin surface quality and a flawlessly even skin tone. \r\n\r\nWhich hair type is it good for?\r\nStraight\r\nWavy\r\nCurly\r\nCoiled\r\nTightly Coiled '),
('P078', 'Brazilian 4 Play Moisturizing Shower Cream-Gel', 'SOL DE JANEIRO', 'Body', 'Bath & Shower', 88.99, 'What it is: \r\nA creamy, lathering body wash that gently nourishes and cleanses the skin. \r\n\r\nSolutions for: \r\n- Dryness \r\n- Dullness and uneven texture '),
('P079', 'COCO MADEMOISELLE Foaming Shower Gel', 'CHANEL', 'Body', 'Bath & Shower', 279.99, 'Moisturizing and cleansing gel leaves skin lightly fragranced with the feminine and sexy, young and exciting scent. Produces a rich, creamy foam that cleanses the skin gently, turning the bath or shower into a refreshing, relaxing environment.27'),
('P080', 'Invigorating Rush Hair + Body Wash', 'ANTHONY', 'Body', 'Bath & Shower', 115.99, 'What it is:\r\nA two-in-one formula that cleanses and conditions with a woodsy, refreshing scent. \r\n\r\nWhat it is formulated to do:\r\nRecharge the body and mind with this multitasking formula for hair and body. The unique alpine wood scent is clean and masculine, promising an invigorating rush with every use—perfect for a soothing, post work-out clean. \r\n'),
('P081', 'Body Shower Gel', 'RAHUA', 'Body', 'Bath & Shower', 119.99, 'What it is:\r\nA plant-derived shower gel that gently cleanses and moisturizes while awakening the sense with the invigorating scents of lavender, eucalyptus, vanilla, and palo santo. \r\n\r\nKey benefits: \r\n- Invigorates senses \r\n- Naturally cleanses \r\n- Nourishes skin \r\n'),
('P082', 'Alien Radiant Shower Gel', 'MUGLER', 'Body', 'Bath & Shower', 199.99, 'What it is: \r\nA foaming shower gel enriched with oil and scented with Alien. \r\n\r\nWhat it does: \r\nThis cleansing gel leaves the skin with a feeling of satin and refreshing cleanliness while imparting the intense but never overpowering scent of Alien.'),
('P083', 'KP Duty Body Scrub', 'DERMADOCTOR', 'Body', 'Moisturizer', 249.99, 'What it is:\r\nA dermatologist formulated body scrub with chemical and physical exfoliation. \r\n\r\nWhat it is formulated to do:\r\nThis dual-action exfoliator combines the benefits of a chemical peel and a microdermabrasion into a single, easy-to-use formulation. '),
('P084', 'Argan Sugar Balm Body Scrub\r\n', 'JOSIE MARAN', 'Body', 'Moisturizer', 159.99, 'What it is:\r\nA hydrating and revitalizing exfoliating scrub featuring 100 percent pure argan oil and delicate sugar crystals. \r\n\r\nSolutions for: \r\n- Dryness\r\n- Dullness and uneven texture\r\n'),
('P085', 'Acne Face & Body Scrub', 'PETER THOMAS ROTH ', 'Body', 'Moisturizer', 117.99, 'Which skin type is it good for?\r\n? Normal\r\n? Oily\r\n? Combination\r\n? Dry\r\n? Sensitive \r\n\r\nWhat it is:\r\nAn ultra-gentle yet effective acne scrub that cleanses, treats, and exfoliates the face and body with one percent salicylic acid.'),
('P086', 'Rose Quartz Illuminating Body Oil', 'HERBIVORE', 'Body', 'Moisturizer', 199.99, 'What it is:\r\nAn illuminating body oil that combines deeply hydrating oils, intoxicating Moroccan Rose, and natural mineral pigments for a subtle shimmer and glow.\r\n\r\nWhich skin type is it good for?\r\n? Normal\r\n? Oily\r\n? Combination\r\n? Dry\r\n? Sensitive '),
('P087', 'Body Soufflé', 'MOROCCANOIL ', 'Body', 'Moisturizer', 239.99, 'What it is: \r\nA whipped body moisturizer infused with argan oil and creamy shea butter for skin that’s soft and smooth. \r\n\r\nWhich skin type is it good for? \r\nNormal \r\nOily \r\nCombination \r\nDry \r\n'),
('P088', 'Ultimate Strength Hand Salve', 'KIEHL\'S SINCE 1851', 'Body', 'Moisturizer', 91.99, 'What it is:\r\nA maximum-strength moisturizer for dry, active hands. \r\n\r\nSolutions for:\r\n- Dryness\r\n- Dullness and uneven textur'),
('P089', 'Hand and Nail Cream', 'CAUDALIE', 'Body', 'Moisturizer', 59.99, 'What it is:\r\nAn antioxidant-rich, moisturizing cream for the hands and nails that provides a silky finish and lasting comfort. \r\n\r\nWhich skin type is it good for?\r\nNormal\r\nOily\r\nCombination\r\nDry\r\nSensitive '),
('P090', 'Mini Bebe Hand Cream\r\n', 'IT\'S SKIN ', 'Body', 'Moisturizer', 19.99, 'What it is:\r\nA travel-size hand cream to moisturize your hands wherever you go. \r\n\r\nSolutions for:\r\n- Dryness\r\n- Dullness and uneven texture '),
('P091', 'Rose Hand Cream', 'JURLIQUE', 'Body', 'Moisturizer', 78.99, 'What it is:\r\nA rich, protective hand cream to moisturize and restore smoothness, leaving hands feeling soft and supple.\r\n\r\nWhich skin type is it good for?\r\n? Normal\r\n? Oily\r\n? Combination\r\n? Dry\r\n? Sensitive\r\n'),
('P092', 'Bergamote Soleil Hand Cream\r\n', 'ATELIER COLOGNE', 'Body', 'Moisturizer', 99.99, 'What it is:\r\nAn oil-based hand cream composed of natural ingredients that leaves the skin soft and lightly perfumed.\r\n\r\nWhat it does:\r\nThis luxurious hand cream is made of from shea butter, which is known for its moisturizing and protectant properties. The formula also includes an overdose of vitamin A, which supports naturally healthy skin and fights free-radicals. Apricot kernel oil softens, soothes, and provides further antioxidant benefit.\r\n'),
('P093', 'Pure Radiant Tinted Moisturizer Broad Spectrum SPF 30', 'NARS ', 'Body', 'Suncare & Selftanner', 179.99, 'What it is:\r\nA lightweight tinted moisturizer that evens skin tone and provides a translucent veil of protection. \r\n\r\nWhat it is formulated to do:\r\nInfused with lush, naturally-derived ingredients, this lightweight tinted moisturizer immediately helps thirsty skin feel hydrated. It has been proven to help reduce the appearance of discoloration and dark spots caused by hyperpigmentation for a clearer and brighter complexion in as little as four weeks. Oil-free and luxurious, it obscures the appearance of lines, wrinkles, pores, and other imperfections while broad spectrum SPF 30 protects skin. '),
('P094', 'Tinted Moisturizer SPF 20 - Illuminating', 'LAURA MERCIER', 'Body', 'Suncare & Selftanner', 179.99, 'What it is:\r\nA moisturizer with a hint of shimmering color.\r\n\r\nWhat it does:\r\nLaura Mercier Tinted Moisturizer Illuminating is a lightweight, buildable sheer foundation formula that delivers a youthful, radiant finish.\r\n'),
('P095', 'Umbra Tinte Physical Daily Defense Broad Spectrum Sunscreen SPF 30', 'DRUNK ELEPHANT ', 'Body', 'Suncare & Selftanner', 359.99, 'What it is:\r\nA tinted, physical sunscreen that delivers powerful broad-spectrum UVA/UVB protection and helps aid in the prevention of free radical and oxidative damage as well as photoaging for a more youthful-looking complexion—delivering a hint of tint for a gorgeous, glowing finish.\r\n\r\nWhich skin type is it good for?\r\nNormal\r\nOily\r\nCombination\r\nDry\r\nSensitive '),
('P096', 'Ultimate Sun Protection Lotion Broad Spectrum SPF 50+ WetForce for Sensitiv', 'SHISEIDO', 'Body', 'Suncare & Selftanner', 169.99, 'What it is: \r\nA new formulation of the popular Ultimate Sun Protection Lotion with WetForce, now with ingredients selected especially for sensitive skin and children\'s skin. \r\n\r\nWhat it is formulated to do: \r\nThis superior, mineral-based, high protection sunscreen for face and body is free from chemical sunscreen agents, fragrance, alcohol, parabens and has a texture gentle enough for the most delicate skin. The low-irritant formula also features Shiseido\'s exclusive WetForce technology, so it becomes even more powerful when the applied area is exposed to water or perspiration for 15 minutes. '),
('P097', 'Sunless Tan Dry Body Oil Mist', 'COOLA', 'Body', 'Suncare & Selftanner', 187.99, 'What it is:\r\nAn easy-to-use, eco-certified cosmos organic sunless tan body mist that delivers a natural-looking, buildable radiance that lasts up to three days. \r\n\r\nWhich skin type is it good for?\r\nNormal\r\nOily\r\nCombination\r\nDry\r\nSensitive '),
('P098', 'After Sun Greek Yoghurt Cooling Gel for Face and Body', 'KORRES ', 'Body', 'Suncare & Selftanner', 103.99, 'What it is:\r\nA cooling after-sun cream gel for face and body, made with real Greek Yoghurt.\r\n\r\nWhich skin type is it good for?\r\nNormal\r\nOily\r\nCombination\r\nDry\r\nSensitive\r\n'),
('P099', 'After-Sun Milk Soothing Body Lotion', 'MOROCCANOIL', 'Body', 'Suncare & Selftanner', 107.99, 'What it is: \r\nA lightweight, soothing body lotion that enhances and extends your sunkissed glow while nourishing and hydrating skin. \r\n\r\nWhich skin type is it good for? \r\nNormal \r\nOily \r\nCombination \r\nDry\r\n');
INSERT INTO `Products` (`productID`, `productName`, `productBrand`, `category`, `subcategory`, `price`, `productDesc`) VALUES
('P100', 'Radiance-Plus Golden Glow Booster', 'CLARINS', 'Body', 'Suncare & Selftanner', 127.99, 'What it is:\r\nA skin booster to be mixed with your day and night cream for a radiant, sunkissed glow. \r\n\r\nWhat it is formulated to do:\r\nThree drops to sunkissed skin. This is the first ever self-tanning innovation from the Clarins laboratories. From sunkissed to sun-drenched, simply mix with your regular day or night cream to gradually develop natural-looking, beautifully bronzed skin. Golden Glow Booster\'s 99.8 percent natural formula combines natural DHA and erythrulose with aloe vera extract to help preserve skin\'s softness while giving your complexion a healthy-looking glow. '),
('P101', 'THE FACE Illuminating Self-Tan Drops', 'TAN-LUXE', 'Body', 'Suncare & Selftanner', 249.99, 'What it is:\r\nA tanning concentrate that transforms any moisturizer, serum, or face oil into a custom self tanner.\r\n\r\nWhich skin type is it good for?\r\nNormal\r\nOily\r\nCombination\r\nDry\r\nSensitive\r\n');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `account`
--
ALTER TABLE `Account`
  ADD PRIMARY KEY (`username`);

--
-- Indexes for table `Products`
--
ALTER TABLE `Products`
  ADD PRIMARY KEY (`productID`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
